plugins:
  mediawiki_enabled:
    default: false
    client: false
  mediawiki_api_path:
    default: ""
    client: false
  mediawiki_validate_tls:
    default: true
    client: false
  mediawiki_host_override:
    default: ""
    client: false
